class Constants {
  static const Map<String, List<Map<String, dynamic>>> allTypes = {
    "Python": [
      {
        'id': 'basic',
        'title': 'Basics',
        'tier': 'free',
        'topics': ["variables", "datatypes", "type conversion"],
      },
      {
        'id': 'flow',
        'title': 'Flow Control',
        'tier': 'free',
        'topics': [
          "if...else",
          "for loop",
          "while loop",
          "break & continue",
          "pass",
        ],
      },
      {
        'id': 'function',
        'title': 'Functions',
        'tier': 'free',
        'topics': [
          "argument",
          "recursion",
          "anonymous function",
          "global and local",
        ],
      },
      {
        'id': 'file',
        'title': 'File Handling',
        'tier': 'free',
        'topics': [
          "file operation",
          "directory",
          "exception",
          "exception handling",
          "user-defined exception",
        ],
      },
      {
        'id': 'oops',
        'title': 'OOPs',
        'tier': 'vip',
        'topics': [
          "OOP",
          "class",
          "inheritance",
          "multiple inheritance",
          "operator overloading",
        ],
      },
      {
        'id': 'advanced',
        'title': 'Advanced',
        'tier': 'vip',
        'topics': [
          "iterator",
          "generator",
          "closure",
          "decorators",
          "property",
          "RegEx",
        ],
      },
    ],
    "Databases & SQL with Python": [
      {
        'id': 'sql_fundamental',
        'title': 'SQL Fundamentals',
        'tier': 'free',
        'topics': [
          "SELECT",
          "INSERT",
          "UPDATE",
          "DELETE",
          "WHERE",
          "ORDER BY",
          "LIMIT",
          "DISTINCT",
          "aliases",
          "CASE WHEN",
        ],
      },
      {
        'id': 'joins_subquerie',
        'title': 'Joins, Subqueries & CTEs',
        'tier': 'free',
        'topics': [
          "INNER/LEFT/RIGHT/FULL JOIN",
          "self-joins",
          "nested subqueries",
          "correlated subqueries",
          "WITH clause",
          "recursive CTEs",
        ],
      },
      {
        'id': 'aggregations_in',
        'title': 'Aggregations & Indexes',
        'tier': 'free',
        'topics': [
          "GROUP BY",
          "HAVING",
          "COUNT/SUM/AVG/MIN/MAX",
          "ROLLUP",
          "CREATE INDEX",
          "composite indexes",
          "EXPLAIN ANALYZE",
        ],
      },
      {
        'id': 'sqlite_postgres',
        'title': 'SQLite & PostgreSQL',
        'tier': 'free',
        'topics': [
          "`sqlite3`",
          "in-memory DBs",
          "psycopg2",
          "connection pooling",
          "transactions",
          "JSONB",
          "COPY command",
        ],
      },
      {
        'id': 'mysql_database',
        'title': 'MySQL & Database Design',
        'tier': 'free',
        'topics': [
          "`mysql-connector`",
          "PyMySQL",
          "stored procedures",
          "normalization (1NF–3NF)",
          "ER diagrams",
          "schema design",
        ],
      },
      {
        'id': 'sqlalchemy_core',
        'title': 'SQLAlchemy Core & ORM',
        'tier': 'vip',
        'topics': [
          "Engine",
          "MetaData",
          "Table",
          "`select/insert/update/delete`",
          "Declarative models",
          "sessions",
          "relationships",
          "lazy/eager loading",
        ],
      },
      {
        'id': 'migrations_tran',
        'title': 'Migrations & Transactions',
        'tier': 'vip',
        'topics': [
          "Alembic `revision/upgrade/downgrade`",
          "autogenerate",
          "ACID properties",
          "isolation levels",
          "rollback",
          "savepoints",
        ],
      },
      {
        'id': 'nosql_mongodb_r',
        'title': 'NoSQL — MongoDB & Redis',
        'tier': 'vip',
        'topics': [
          "`pymongo`",
          "BSON",
          "`aggregate`",
          "`\$lookup`",
          "`redis-py`",
          "TTL",
          "pub/sub",
          "sorted sets",
          "Redis as cache/queue",
        ],
      },
    ],
    "Web Scraping & Automation": [
      {
        'id': 'http_requests_a',
        'title': 'HTTP, Requests & APIs',
        'tier': 'free',
        'topics': [
          "GET/POST/PUT/DELETE",
          "headers",
          "cookies",
          "sessions",
          "auth",
          "pagination",
          "rate limiting",
          "OAuth tokens",
        ],
      },
      {
        'id': 'html_parsing_xp',
        'title': 'HTML Parsing & XPath',
        'tier': 'free',
        'topics': [
          "BeautifulSoup4 `find/find_all`",
          "CSS selectors",
          "lxml `etree`",
          "XPath axes",
          "predicates",
        ],
      },
      {
        'id': 'scrapy_framewor',
        'title': 'Scrapy Framework',
        'tier': 'free',
        'topics': [
          "Spiders",
          "`CrawlSpider`",
          "`Item`",
          "`ItemPipeline`",
          "middlewares",
          "`LinkExtractor`",
          "`FormRequest`",
          "feed exports",
        ],
      },
      {
        'id': 'selenium_playwr',
        'title': 'Selenium & Playwright',
        'tier': 'free',
        'topics': [
          "WebDriver",
          "`find_element`",
          "waits",
          "`ActionChains`",
          "headless mode",
          "`async_playwright`",
          "network interception",
          "device emulation",
        ],
      },
      {
        'id': 'javascript_heav',
        'title': 'JavaScript-Heavy & Dynamic Sites',
        'tier': 'vip',
        'topics': [
          "Infinite scroll",
          "SPAs",
          "`execute_script`",
          "waiting for dynamic content",
          "iframe handling",
        ],
      },
      {
        'id': 'anti_scraping_e',
        'title': 'Anti-Scraping & Ethics',
        'tier': 'vip',
        'topics': [
          "`fake_useragent`",
          "rotating proxies",
          "`cloudscraper`",
          "`robots.txt`",
          "`crawl-delay`",
          "legal considerations",
        ],
      },
      {
        'id': 'data_storage_sc',
        'title': 'Data Storage & Scheduling',
        'tier': 'vip',
        'topics': [
          "Saving to CSV/JSON/SQLite/MongoDB",
          "`APScheduler`",
          "`cron`",
          "`CrawlerProcess`",
          "cloud deployment",
        ],
      },
    ],
    "FastAPI": [
      {
        'id': 'routing_request',
        'title': 'Routing & Request Handling',
        'tier': 'free',
        'topics': [
          "Path/query params",
          "`@app.get/post/put/delete`",
          "default values",
          "type hints",
          "HTTP status codes",
        ],
      },
      {
        'id': 'pydantic_valida',
        'title': 'Pydantic & Validation',
        'tier': 'free',
        'topics': [
          "`BaseModel`",
          "`Field`",
          "`validator`",
          "`root_validator`",
          "`constr/conint`",
          "nested models",
          "`response_model`",
        ],
      },
      {
        'id': 'dependency_inje',
        'title': 'Dependency Injection & Middleware',
        'tier': 'free',
        'topics': [
          "`Depends`",
          "nested/class-based deps",
          "`BaseHTTPMiddleware`",
          "CORS",
          "GZip",
          "request logging",
        ],
      },
      {
        'id': 'authentication',
        'title': 'Authentication & Authorization',
        'tier': 'free',
        'topics': [
          "OAuth2 password flow",
          "JWT with `python-jose`",
          "refresh tokens",
          "role-based access",
          "permission scopes",
        ],
      },
      {
        'id': 'database_files',
        'title': 'Database, Files & WebSockets',
        'tier': 'vip',
        'topics': [
          "SQLAlchemy async",
          "`AsyncSession`",
          "`UploadFile`",
          "multi-file upload",
          "`WebSocket`",
          "broadcasting",
        ],
      },
      {
        'id': 'error_handling',
        'title': 'Error Handling & Testing',
        'tier': 'vip',
        'topics': [
          "`HTTPException`",
          "custom exception handlers",
          "`422` responses",
          "`TestClient`",
          "`AsyncClient`",
          "mocking deps",
        ],
      },
      {
        'id': 'api_design_depl',
        'title': 'API Design & Deployment',
        'tier': 'vip',
        'topics': [
          "`APIRouter`",
          "versioning",
          "OpenAPI/Swagger/ReDoc",
          "Uvicorn",
          "Gunicorn workers",
          "Docker",
          "health checks",
        ],
      },
    ],
    "Testing in Python": [
      {
        'id': 'unittest',
        'title': 'unittest',
        'tier': 'free',
        'topics': [
          "`TestCase`",
          "`setUp/tearDown`",
          "`setUpClass`",
          "assertions",
          "`skipIf`",
          "`expectedFailure`",
          "`subTest`",
          "test suites",
        ],
      },
      {
        'id': 'pytest_fundamen',
        'title': 'pytest Fundamentals',
        'tier': 'free',
        'topics': [
          "Test functions",
          "`assert`",
          "`pytest.raises`",
          "`pytest.warns`",
          "`-v/-k/-x` flags",
          "markers",
          "test discovery",
        ],
      },
      {
        'id': 'fixtures_parame',
        'title': 'Fixtures & Parametrize',
        'tier': 'free',
        'topics': [
          "`@pytest.fixture`",
          "scope (function/class/module/session)",
          "`yield`",
          "`conftest.py`",
          "`@pytest.mark.parametrize`",
        ],
      },
      {
        'id': 'mocking',
        'title': 'Mocking',
        'tier': 'free',
        'topics': [
          "`unittest.mock.patch`",
          "`MagicMock`",
          "`return_value`",
          "`side_effect`",
          "patching builtins/datetime/requests",
        ],
      },
      {
        'id': 'coverage_tdd_bd',
        'title': 'Coverage, TDD & BDD',
        'tier': 'vip',
        'topics': [
          "`coverage.py`",
          "branch coverage",
          "`.coveragerc`",
          "Red-Green-Refactor",
          "Gherkin",
          "`pytest-bdd`",
          "step definitions",
        ],
      },
      {
        'id': 'api_database_te',
        'title': 'API & Database Testing',
        'tier': 'vip',
        'topics': [
          "`responses`",
          "`httpretty`",
          "`respx`",
          "test DBs",
          "transactional rollback",
          "`factory_boy`",
          "contract testing",
        ],
      },
      {
        'id': 'performance_bes',
        'title': 'Performance & Best Practices',
        'tier': 'vip',
        'topics': [
          "`locust`",
          "`pytest-benchmark`",
          "`timeit`",
          "AAA pattern",
          "test isolation",
          "naming conventions",
          "snapshot testing",
        ],
      },
    ],
    "Python Concurrency & Performance": [
      {
        'id': 'threading',
        'title': 'Threading',
        'tier': 'free',
        'topics': [
          "`Thread`",
          "`start/join`",
          "daemon threads",
          "`Lock`",
          "`RLock`",
          "`Semaphore`",
          "`Event`",
          "`Condition`",
          "`Barrier`",
        ],
      },
      {
        'id': 'gil_multiproces',
        'title': 'GIL & Multiprocessing',
        'tier': 'free',
        'topics': [
          "GIL internals",
          "CPU-bound vs I/O-bound",
          "`Process`",
          "`Queue`",
          "`Pipe`",
          "`Value/Array`",
          "shared memory",
        ],
      },
      {
        'id': 'multiprocessing',
        'title': 'Multiprocessing Pool',
        'tier': 'free',
        'topics': [
          "`Pool.map`",
          "`starmap`",
          "`imap`",
          "`apply_async`",
          "chunksize tuning",
          "`concurrent.futures` `ProcessPoolExecutor`",
        ],
      },
      {
        'id': 'asyncio',
        'title': 'AsyncIO',
        'tier': 'free',
        'topics': [
          "`async/await`",
          "event loop",
          "coroutines",
          "`asyncio.gather`",
          "`create_task`",
          "`TaskGroup`",
          "cancellation",
          "`asyncio.Queue`",
        ],
      },
      {
        'id': 'async_patterns',
        'title': 'Async Patterns & HTTP',
        'tier': 'vip',
        'topics': [
          "Producer-consumer",
          "semaphore-limited concurrency",
          "`aiohttp`",
          "`ClientSession`",
          "async scraping",
        ],
      },
      {
        'id': 'celery_task_que',
        'title': 'Celery & Task Queues',
        'tier': 'vip',
        'topics': [
          "Task definition",
          "Redis/RabbitMQ brokers",
          "`delay`",
          "`apply_async`",
          "chaining",
          "retries",
          "`beat` scheduler",
        ],
      },
      {
        'id': 'profiling_optim',
        'title': 'Profiling & Optimization',
        'tier': 'vip',
        'topics': [
          "`cProfile`",
          "`line_profiler`",
          "`tracemalloc`",
          "`__slots__`",
          "generators",
          "`lru_cache`",
          "Cython",
          "Numba `@jit`",
        ],
      },
    ],
    "Python for DevOps & Cloud": [
      {
        'id': 'os_shell_file_a',
        'title': 'OS, Shell & File Automation',
        'tier': 'free',
        'topics': [
          "`os`",
          "`sys`",
          "`subprocess`",
          "`shutil`",
          "`pathlib`",
          "`glob`",
          "`tempfile`",
          "`watchdog`",
          "environment variables",
        ],
      },
      {
        'id': 'config_secrets',
        'title': 'Config, Secrets & SSH',
        'tier': 'free',
        'topics': [
          "`configparser`",
          "`dotenv`",
          "`PyYAML`",
          "TOML",
          "`pydantic-settings`",
          "`paramiko`",
          "`fabric`",
          "SFTP",
          "Vault",
        ],
      },
      {
        'id': 'docker_kubernet',
        'title': 'Docker & Kubernetes',
        'tier': 'free',
        'topics': [
          "`docker` SDK",
          "images/containers/volumes",
          "`DockerClient`",
          "`kubernetes` client",
          "pods",
          "deployments",
          "config maps",
        ],
      },
      {
        'id': 'aws_with_boto3',
        'title': 'AWS with Boto3',
        'tier': 'free',
        'topics': [
          "S3 CRUD",
          "EC2 management",
          "Lambda invocation",
          "IAM",
          "SQS",
          "SNS",
          "DynamoDB",
          "presigned URLs",
        ],
      },
      {
        'id': 'google_cloud_az',
        'title': 'Google Cloud & Azure',
        'tier': 'vip',
        'topics': [
          "GCS",
          "BigQuery",
          "Pub/Sub",
          "Cloud Functions",
          "Firestore",
          "Azure Blob",
          "Cosmos DB",
          "Service Bus",
        ],
      },
      {
        'id': 'infrastructure',
        'title': 'Infrastructure as Code',
        'tier': 'vip',
        'topics': [
          "`pulumi` with Python",
          "CDK for Terraform",
          "managing cloud infra programmatically",
          "stack outputs",
        ],
      },
      {
        'id': 'logging_monitor',
        'title': 'Logging, Monitoring & CI/CD',
        'tier': 'vip',
        'topics': [
          "`logging`",
          "`loguru`",
          "Sentry SDK",
          "GitHub Actions Python steps",
          "pipeline API triggers",
          "structured logs",
        ],
      },
    ],
    "Cybersecurity with Python": [
      {
        'id': 'cryptography_ha',
        'title': 'Cryptography & Hashing',
        'tier': 'free',
        'topics': [
          "`hashlib`",
          "MD5/SHA-256/SHA-512",
          "`hmac`",
          "salting",
          "Base64",
          "Fernet",
          "AES (CBC/GCM)",
          "RSA",
          "EC keys",
        ],
      },
      {
        'id': 'password_token',
        'title': 'Password & Token Security',
        'tier': 'free',
        'topics': [
          "`bcrypt`",
          "`argon2-cffi`",
          "`passlib`",
          "JWT structure",
          "signing with `python-jose`",
          "expiry",
          "refresh tokens",
        ],
      },
      {
        'id': 'tls_https_secur',
        'title': 'TLS, HTTPS & Secure Coding',
        'tier': 'free',
        'topics': [
          "`ssl` module",
          "cert verification",
          "`certifi`",
          "safe `subprocess`",
          "avoiding `eval/exec`",
          "`pip-audit`",
          "`bandit`",
        ],
      },
      {
        'id': 'network_scannin',
        'title': 'Network Scanning & Analysis',
        'tier': 'vip',
        'topics': [
          "`socket`",
          "port scanning",
          "banner grabbing",
          "`scapy` packet crafting",
          "`python-nmap`",
          "Wireshark integration",
        ],
      },
      {
        'id': 'owasp_top_10_we',
        'title': 'OWASP Top 10 & Web Security',
        'tier': 'vip',
        'topics': [
          "SQL injection",
          "XSS",
          "IDOR",
          "broken auth",
          "CSP/HSTS headers — identifying and testing with Python",
        ],
      },
      {
        'id': 'forensics_stega',
        'title': 'Forensics, Steganography & CTF',
        'tier': 'vip',
        'topics': [
          "Hex dump",
          "metadata extraction",
          "`python-magic`",
          "LSB steganography",
          "`pwntools`",
          "format strings",
          "binary exploitation",
        ],
      },
    ],
    "Data Visualization": [
      {
        'id': 'seaborn',
        'title': 'Seaborn',
        'tier': 'free',
        'topics': [
          "`scatterplot`",
          "`lineplot`",
          "`boxplot`",
          "`violinplot`",
          "`heatmap`",
          "`pairplot`",
          "`FacetGrid`",
          "themes",
          "statistical annotations",
        ],
      },
      {
        'id': 'plotly',
        'title': 'Plotly',
        'tier': 'free',
        'topics': [
          "`px.bar/scatter/line/choropleth/sunburst/treemap`",
          "`go.Figure`",
          "subplots",
          "secondary axes",
          "animations",
          "sliders",
        ],
      },
      {
        'id': 'bokeh_altair',
        'title': 'Bokeh & Altair',
        'tier': 'free',
        'topics': [
          "`ColumnDataSource`",
          "`HoverTool`",
          "widgets",
          "`mark_point/line`",
          "`transform_filter/aggregate`",
          "compositing",
          "server apps",
        ],
      },
      {
        'id': 'matplotlib_adva',
        'title': 'Matplotlib Advanced',
        'tier': 'free',
        'topics': [
          "`GridSpec`",
          "twin axes",
          "`Axes3D`",
          "`FuncAnimation`",
          "custom colormaps",
          "`rcParams`",
          "publication-quality figures",
        ],
      },
      {
        'id': 'dash_streamlit',
        'title': 'Dash & Streamlit',
        'tier': 'vip',
        'topics': [
          "`dcc.Graph`",
          "`@callback`",
          "`DataTable`",
          "`st.slider`",
          "`st.session_state`",
          "caching",
          "multipage apps",
          "deployment",
        ],
      },
      {
        'id': 'geospatial_text',
        'title': 'Geospatial & Text Viz',
        'tier': 'vip',
        'topics': [
          "Folium `Map/Marker/Choropleth/HeatMap`",
          "`WordCloud`",
          "`networkx` graph plots",
          "`pygal` SVG charts",
        ],
      },
      {
        'id': 'chart_best_prac',
        'title': 'Chart Best Practices',
        'tier': 'vip',
        'topics': [
          "Choosing chart types",
          "color accessibility (WCAG)",
          "avoiding chartjunk",
          "aspect ratios",
          "D3.js via `mpld3`",
        ],
      },
    ],
    "Python for AI Agents & LLMs": [
      {
        'id': 'openai_api_prom',
        'title': 'OpenAI API & Prompt Engineering',
        'tier': 'free',
        'topics': [
          "`chat.completions.create`",
          "roles",
          "`temperature/max_tokens/stream`",
          "zero-shot",
          "few-shot",
          "chain-of-thought",
          "function calling",
        ],
      },
      {
        'id': 'langchain_core',
        'title': 'LangChain Core',
        'tier': 'free',
        'topics': [
          "`ChatOpenAI`",
          "`PromptTemplate`",
          "`LLMChain`",
          "`StrOutputParser`",
          "`RunnableSequence`",
          "memory types",
        ],
      },
      {
        'id': 'langchain_agent',
        'title': 'LangChain Agents & Tools',
        'tier': 'free',
        'topics': [
          "`AgentExecutor`",
          "`create_react_agent`",
          "`Tool`",
          "`StructuredTool`",
          "custom tools",
          "multi-tool use",
        ],
      },
      {
        'id': 'rag_vector_data',
        'title': 'RAG & Vector Databases',
        'tier': 'free',
        'topics': [
          "Document loaders",
          "text splitters",
          "embeddings",
          "`RetrievalQA`",
          "Chroma",
          "FAISS",
          "Pinecone",
          "metadata filtering",
        ],
      },
      {
        'id': 'hugging_face_fi',
        'title': 'Hugging Face & Fine-Tuning',
        'tier': 'vip',
        'topics': [
          "`pipeline`",
          "`AutoModel/AutoTokenizer`",
          "`from_pretrained`",
          "LoRA",
          "PEFT",
          "`SFTTrainer`",
          "evaluation metrics",
        ],
      },
      {
        'id': 'multi_agent_fra',
        'title': 'Multi-Agent & Frameworks',
        'tier': 'vip',
        'topics': [
          "LlamaIndex `VectorStoreIndex`",
          "`AutoGen`",
          "`CrewAI`",
          "agent roles",
          "task delegation",
          "tool sharing",
        ],
      },
      {
        'id': 'deployment_safe',
        'title': 'Deployment, Safety & Observability',
        'tier': 'vip',
        'topics': [
          "FastAPI + LLM",
          "streaming",
          "async inference",
          "`guardrails-ai`",
          "PII detection",
          "`LangSmith`",
          "token tracking",
        ],
      },
    ],
    "Python Packaging & Best Practices": [
      {
        'id': 'environments_pr',
        'title': 'Environments & Project Structure',
        'tier': 'free',
        'topics': [
          "`venv`",
          "`poetry`",
          "`pipenv`",
          "`conda`",
          "`src` layout",
          "`__init__.py`",
          "`__main__.py`",
          "namespace packages",
        ],
      },
      {
        'id': 'pyproject_toml',
        'title': 'pyproject.toml & Dependency Management',
        'tier': 'free',
        'topics': [
          "[build-system/project/tool]",
          "pip-compile",
          "lock files",
          "version pinning",
          "bumpversion",
        ],
      },
      {
        'id': 'publishing_type',
        'title': 'Publishing & Type Hints',
        'tier': 'free',
        'topics': [
          "build",
          "twine",
          "TestPyPI",
          "wheels",
          "str/int/List/Dict/Optional/Union/Literal/TypeVar/Protocol",
        ],
      },
      {
        'id': 'static_analysis',
        'title': 'Static Analysis & Code Style',
        'tier': 'free',
        'topics': [
          "`mypy --strict`",
          "`py.typed`",
          "`black`",
          "`ruff`",
          "`flake8`",
          "`isort`",
          "`pylint`",
          "pre-commit hooks",
        ],
      },
      {
        'id': 'documentation_d',
        'title': 'Documentation & Dunder Methods',
        'tier': 'vip',
        'topics': [
          "Google/NumPy/Sphinx docstrings",
          "`sphinx-apidoc`",
          "Read the Docs",
          "`__repr__/str/eq/hash/iter/enter/exit`",
        ],
      },
      {
        'id': 'design_patterns',
        'title': 'Design Patterns',
        'tier': 'vip',
        'topics': [
          "Singleton",
          "Factory",
          "Observer",
          "Decorator",
          "Strategy",
          "Command",
          "Metaclasses",
          "descriptors",
          "`property`",
        ],
      },
      {
        'id': 'solid_clean_cod',
        'title': 'SOLID, Clean Code & Security',
        'tier': 'vip',
        'topics': [
          "SRP/OCP/LSP/ISP/DIP",
          "DRY",
          "YAGNI",
          "early returns",
          "`bandit`",
          "safe YAML",
          "`eval/exec` avoidance",
        ],
      },
    ],
  };

  static const List<AllLanguages> allLanguages = [
    AllLanguages(name: 'Python', apiName: 'python', tier: LangTier.free),
    AllLanguages(name: 'Django', apiName: 'django', tier: LangTier.vip),
    AllLanguages(name: 'SQL', apiName: 'sql', tier: LangTier.vip),
  ];
}

enum LangTier { free, vip }

class AllLanguages {
  final String name;
  final String apiName;
  final LangTier tier;

  const AllLanguages({
    required this.name,
    required this.apiName,
    required this.tier,
  });
}
